@baseURL = http://127.0.0.1:5000

GET {{baseURL}}/

### Register
POST {{baseURL}}/register
Content-Type: application/json

{
    "username": "cmh5",
    "password": "123"
}

### Login
# @name login
POST {{baseURL}}/login
Content-Type: application/json

{
    "username": "cmh",
    "password": "123"
}
###
@token = {{login.response.body.data.token}}

GET {{baseURL}}/me
Authorization: Bearer {{token}}



### get or create direct conversation
POST {{baseURL}}/conversations/direct
Authorization: Bearer {{token}}
Content-Type: application/json 

{
    "target_user_id": "avx"
}

### list conversations paginated
GET {{baseURL}}/conversations?page=1&page_size=10&sort=id&order=asc&keyword=
Authorization: Bearer {{token}}

### get conversation
GET {{baseURL}}/conversations/2
Authorization: Bearer {{token}}